{"author":{"id":"abaf2135d6e2596615e5078259d6eb07724224ee44d800c3a915e20c525bd307"},"ops":[{"type":1,"timestamp":1636478596,"nonce":"T+QUIGMcuGT0YxT+BiCJO2WXZNA=","metadata":{"github-id":"I_kwDOBLCY8M4-hJek","github-url":"https://github.com/svpcom/wfb-ng/issues/174","origin":"github"},"title":"[BUG] Can't Make On Ubuntu","message":"Machine:\n\n```\n$ lsb_release -a\nNo LSB modules are available.\nDistributor ID:\tUbuntu\nDescription:\tUbuntu 20.04.3 LTS\nRelease:\t20.04\nCodename:\tfocal\n```\n\nHere is what I get when running `make deb`.\n```\ndh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 11) line 1.\nBEGIN failed--compilation aborted at (eval 11) line 1.\n```","files":null}]}