{"author":{"id":"c55a92a0f265a6db48dd33b19319ac8aa2815cbfed83ba3f1f801e2d216ed737"},"ops":[{"type":3,"timestamp":1719037277,"nonce":"6VjObtlANnIt/vHvaIj3UeRv1ZM=","metadata":{"github-id":"IC_kwDOBLCY8M6CKrSm","github-url":"https://github.com/svpcom/wfb-ng/issues/349#issuecomment-2183836838"},"message":"\u003e readfp\n\nThis is what I'm getting when I run  `sudo journalctl -xu wifibroadcast@gs`:\n```\nJun 17 11:40:51 X570-PC wfb-server[11675]: Traceback (most recent call last):\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/config_parser.py\", line 77, in parse_\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     config.readfp(fd, filename=filename)\nJun 17 11:40:51 X570-PC wfb-server[11675]:     ^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]: AttributeError: 'RawConfigParser' object has no attribute 'readfp'. Did you mean: '\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]: During handling of the above exception, another exception occurred:\nJun 17 11:40:51 X570-PC wfb-server[11675]: Traceback (most recent call last):\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/bin/wfb-server\", line 33, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     sys.exit(load_entry_point('wfb-ng==23.8.141.53708', 'console_scripts', 'wfb-ser\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/bin/wfb-server\", line 25, in importlib_load_entry_point\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return next(matches).load()\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3.12/importlib/metadata/__init__.py\", line 205, in load\nJun 17 11:40:51 X570-PC wfb-server[11675]:     module = import_module(match.group('module'))\nJun 17 11:40:51 X570-PC wfb-server[11675]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return _bootstrap._gcd_import(name[level:], package, level)\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1387, in _gcd_import\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1360, in _find_and_load\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1331, in _find_and_load_unlocked\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 935, in _load_unlocked\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 995, in exec_module\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 488, in _call_with_frames_removed\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/server.py\", line 36, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     from .common import abort_on_crash, exit_status, df_sleep\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/common.py\", line 24, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     from .conf import settings\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/conf/__init__.py\", line 17, in \u003cmodul\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     settings, cfg_files = _parse_config()\nJun 17 11:40:51 X570-PC wfb-server[11675]:                           ^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/conf/__init__.py\", line 14, in _parse\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return config_parser.parse_config(os.path.join(os.getcwd(), os.path.dirname(__f\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/config_parser.py\", line 79, in parse_\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     raise ConfigError(v)\nJun 17 11:40:51 X570-PC wfb-server[11675]: wfb_ng.config_parser.ConfigError: 'RawConfigParser' object has no attribute 'readfp'\nJun 17 11:40:51 X570-PC systemd[1]: wifibroadcast@gs.service: Main process exited, code=exited, status=1/FAILURE\n```\n\nI am not familiar with Python. Not sure why the build contains the incorrect function name.","files":null},{"type":6,"timestamp":1719037315,"nonce":"CxoFuBfOdzvU6KdQgwgi8lUUS98=","metadata":{"github-id":"UCE_lALOBLCY8M6CKrSmzkkqM3I"},"target":"8edee72a6f68e20404729a654ff1e32894a5fb70693bb9d254a34b4a5ccb0a85","message":"\u003e `sudo journalctl -xu wifibroadcast@gs` see troubleshooting guide in wiki\n\nThis is what I'm getting when I run  `sudo journalctl -xu wifibroadcast@gs`:\n```\nJun 17 11:40:51 X570-PC wfb-server[11675]: Traceback (most recent call last):\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/config_parser.py\", line 77, in parse_\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     config.readfp(fd, filename=filename)\nJun 17 11:40:51 X570-PC wfb-server[11675]:     ^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]: AttributeError: 'RawConfigParser' object has no attribute 'readfp'. Did you mean: '\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]: During handling of the above exception, another exception occurred:\nJun 17 11:40:51 X570-PC wfb-server[11675]: Traceback (most recent call last):\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/bin/wfb-server\", line 33, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     sys.exit(load_entry_point('wfb-ng==23.8.141.53708', 'console_scripts', 'wfb-ser\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/bin/wfb-server\", line 25, in importlib_load_entry_point\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return next(matches).load()\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3.12/importlib/metadata/__init__.py\", line 205, in load\nJun 17 11:40:51 X570-PC wfb-server[11675]:     module = import_module(match.group('module'))\nJun 17 11:40:51 X570-PC wfb-server[11675]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3.12/importlib/__init__.py\", line 90, in import_module\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return _bootstrap._gcd_import(name[level:], package, level)\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1387, in _gcd_import\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1360, in _find_and_load\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 1331, in _find_and_load_unlocked\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 935, in _load_unlocked\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 995, in exec_module\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"\u003cfrozen importlib._bootstrap\u003e\", line 488, in _call_with_frames_removed\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/server.py\", line 36, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     from .common import abort_on_crash, exit_status, df_sleep\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/common.py\", line 24, in \u003cmodule\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     from .conf import settings\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/conf/__init__.py\", line 17, in \u003cmodul\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     settings, cfg_files = _parse_config()\nJun 17 11:40:51 X570-PC wfb-server[11675]:                           ^^^^^^^^^^^^^^^\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/conf/__init__.py\", line 14, in _parse\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     return config_parser.parse_config(os.path.join(os.getcwd(), os.path.dirname(__f\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:   File \"/usr/lib/python3/dist-packages/wfb_ng/config_parser.py\", line 79, in parse_\u003e\nJun 17 11:40:51 X570-PC wfb-server[11675]:     raise ConfigError(v)\nJun 17 11:40:51 X570-PC wfb-server[11675]: wfb_ng.config_parser.ConfigError: 'RawConfigParser' object has no attribute 'readfp'\nJun 17 11:40:51 X570-PC systemd[1]: wifibroadcast@gs.service: Main process exited, code=exited, status=1/FAILURE\n```\n\nI am not familiar with Python. Not sure why the build contains the incorrect function name.","files":null},{"type":3,"timestamp":1719228246,"nonce":"pxRSmzK9lucuoM0j/i4B6PPzTNE=","metadata":{"github-id":"IC_kwDOBLCY8M6CUPPY","github-url":"https://github.com/svpcom/wfb-ng/issues/349#issuecomment-2186343384"},"message":"ok..i was able to fix the above error. Install is working.\n\nNow the service is crashing. When i run `sudo service wifibroadcast@gs status`\n\nThis is the error I see:\n\n```\n○ wifibroadcast@gs.service - WFB profile gs\n     Loaded: loaded (/usr/lib/systemd/system/wifibroadcast@.service; disabled; preset: enabled)\n     Active: inactive (dead)\n\nJun 24 16:51:34 X570-PC wfb-server[9506]: [defer.Deferred._runCallbacks #info] # nmcli device show wlx502b73d146e8\nJun 24 16:51:34 X570-PC wfb-server[9506]: [defer.Deferred._runCallbacks #info] # ip link set wlx502b73d146e8 down\nJun 24 16:51:35 X570-PC wfb-server[9506]: [defer.Deferred._runCallbacks #info] # iw dev wlx502b73d146e8 set monitor otherbss\nJun 24 16:51:35 X570-PC wfb-server[9506]: [server.init_wlans #error] RTNETLINK answers: Operation not possible due to RF-kill\nJun 24 16:51:35 X570-PC wfb-server[9506]: [common.abort_on_crash #info] Stopping reactor due to fatal error: RC 2: ip link set wlx502b73d146e8 up\nJun 24 16:51:35 X570-PC wfb-server[9506]: [base.EPollReactor.mainLoop #info] Main loop terminated.\nJun 24 16:51:35 X570-PC wfb-server[9506]: [server.main #info] Exiting with code 1\nJun 24 16:51:35 X570-PC systemd[1]: wifibroadcast@gs.service: Main process exited, code=exited, status=1/FAILURE\nJun 24 16:51:35 X570-PC systemd[1]: wifibroadcast@gs.service: Failed with result 'exit-code'.\nJun 24 16:51:39 X570-PC systemd[1]: Stopped wifibroadcast@gs.service - WFB profile gs.\n```","files":null}]}