{"author":{"id":"2d3729c565bfba136d5fe9f11b9d7d776d7a93f010b7b73cfac8a47ed255bae8"},"ops":[{"type":3,"timestamp":1651092038,"nonce":"Y5leuvWYXIz8WsaoWC3Grrt9haI=","metadata":{"github-id":"IC_kwDOBLCY8M5CP5CY","github-url":"https://github.com/svpcom/wfb-ng/issues/214#issuecomment-1111462040"},"message":"I re-tested without success in the begin of th week.\nI'll try again on friday and i'll get you in touch.","files":null},{"type":3,"timestamp":1652089017,"nonce":"ikjj4jhPUzTlFmvajWKgVyt5agY=","metadata":{"github-id":"IC_kwDOBLCY8M5CzzTz","github-url":"https://github.com/svpcom/wfb-ng/issues/214#issuecomment-1120875763"},"message":"Hello,\n\nI finally managed to make it works. I had to search and delete all old files (python cache) and now it's OK.\n\nThanks a lot!","files":null}]}