{"author":{"id":"ae26fac8ccb805db2175a5f68935360a1ba4e71a79a9becc27bb2b263dab90bc"},"ops":[{"type":3,"timestamp":1561241888,"nonce":"n3dktzfXXq+NErmiM4ympoHuwhk=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDUwNDcwMjM4OA==","github-url":"https://github.com/svpcom/wfb-ng/issues/40#issuecomment-504702388"},"message":"Пересобрал и переустановил пакеты на всякий случай. Проверил все конфиги. \nSTBC на всякий случай выставил в 0\ngs:\n```\ntyoma@Lenovo:~/wifibroadcast/deb_dist$ systemctl daemon-reload\ntyoma@Lenovo:~/wifibroadcast/deb_dist$ systemctl start wifibroadcast@gs\ntyoma@Lenovo:~/wifibroadcast/deb_dist$ systemctl status wifibroadcast@gs\n● wifibroadcast@gs.service - WFB profile gs\n   Loaded: loaded (/lib/systemd/system/wifibroadcast@.service; disabled; vendor \n   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-06-23 01\n  Process: 4856 ExecStart=/usr/bin/python -m telemetry.server gs ${WFB_NICS} (co\n Main PID: 4856 (code=exited, status=1/FAILURE)\n\ntyoma@Lenovo:~/wifibroadcast/deb_dist$ journalctl -xu wifibroadcast@gs\n-- Logs begin at Thu 2019-06-20 21:51:53 EEST, end at Sun 2019-06-23 03:35:57 EE\nиюн 21 00:04:01 Lenovo systemd[1]: Started WFB profile gs.\n-- Subject: Запуск юнита wifibroadcast@gs.service завершен\n-- Defined-By: systemd\n-- Support: http://www.ubuntu.com/support\n-- \n-- Процесс запуска юнита wifibroadcast@gs.service был завершен.\n-- \n-- Результат: RESULT.\nиюн 21 00:04:02 Lenovo python[27181]: 2019-06-21 00:04:02+0300 [-] Log opened.\nиюн 21 00:04:03 Lenovo python[27181]: 2019-06-21 00:04:03+0300 [-] # iw reg set \nиюн 21 00:04:03 Lenovo python[27181]: 2019-06-21 00:04:03+0300 [-] Upon execvpe \nиюн 21 00:04:03 Lenovo python[27181]:         :Traceback (most recent call last)\nиюн 21 00:04:03 Lenovo python[27181]:           File \"/usr/lib/python2.7/dist-pa\nиюн 21 00:04:03 Lenovo python[27181]:             environment)\nиюн 21 00:04:03 Lenovo python[27181]:           File \"/usr/lib/python2.7/dist-pa\nиюн 21 00:04:03 Lenovo python[27181]:             os.execvpe(executable, args, e\nиюн 21 00:04:03 Lenovo python[27181]:           File \"/usr/lib/python2.7/os.py\",\nиюн 21 00:04:03 Lenovo python[27181]:             _execvpe(file, args, env)\nиюн 21 00:04:03 Lenovo python[27181]:           File \"/usr/lib/python2.7/os.py\",\nиюн 21 00:04:03 Lenovo python[27181]:             func(fullname, *argrest)\nиюн 21 00:04:03 Lenovo python[27181]:         OSError: [Errno 2] No such file or\nиюн 21 00:04:03 Lenovo python[27181]: 2019-06-21 00:04:03+0300 [-] Stopping reac\nlines 1-23\n\n```\ndrone:\n```\nrock64@rock64:~/wifibroadcast/deb_dist$ sudo systemctl daemon-reload\nrock64@rock64:~/wifibroadcast/deb_dist$ sudo systemctl start wifibroadcast@dronerock64@rock64:~/wifibroadcast/deb_dist$ sudo systemctl start wifibroadcast@dronerock64@rock64:~/wifibroadcast/deb_dist$ sudo systemctl status wifibroadcast@drone\n● wifibroadcast@drone.service - WFB profile drone\n   Loaded: loaded (/lib/systemd/system/wifibroadcast@.service; disabled; vendor \npreset: enabled)\n   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-06-22 22\n:10:15 UTC; 2s ago\n  Process: 6319 ExecStart=/usr/bin/python -m telemetry.server drone ${WFB_NICS} \n(code=exited, status=1/FAILURE)\n Main PID: 6319 (code=exited, status=1/FAILURE)\n\nJun 22 22:10:15 rock64 systemd[1]: wifibroadcast@drone.service: Failed w\nith result 'exit-code'.\nrock64@rock64:~/wifibroadcast/deb_dist$ journalctl -xu wifibroadcast@drone\n-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Sat 2019-06-22 22:10:31 UTC\n. --\nJun 22 21:40:58 rock64 systemd[1]: Started WFB profile drone.\n-- Subject: Unit wifibroadcast@drone.service has finished start-up\n-- Defined-By: systemd\n-- Support: https://www.debian.org/support\n-- \n-- Unit wifibroadcast@drone.service has finished starting up.\n-- \n-- The start-up result is done.\nJun 22 21:41:01 rock64 python[1817]: 2019-06-22 21:41:01+0000 [-] Log opened.\nJun 22 21:41:01 rock64 python[1817]: 2019-06-22 21:41:01+0000 [-] # iw reg set G\nY\nJun 22 21:41:02 rock64 python[1817]: 2019-06-22 21:41:02+0000 [-] wlan0: ERROR w\nhile getting interface flags: No such device\nJun 22 21:41:02 rock64 python[1817]: 2019-06-22 21:41:02+0000 [-] Stopping react\nor due to fatal error: RC 255: ifconfig wlan0 down\nJun 22 21:41:02 rock64 python[1817]: 2019-06-22 21:41:02+0000 [-] Main loop term\ninated.\nJun 22 21:41:02 rock64 python[1817]: 2019-06-22 21:41:02+0000 [-] Exiting with c\node 1\nJun 22 21:41:02 rock64 systemd[1]: wifibroadcast@drone.service: Main pro\ncess exited, code=exited, status=1/FAILURE\n\n```\nИ вот что ещё интересное нашел. Похоже адаптер не поддерживает настройку мощности\n```\nsudo python -m telemetry.server drone wlx30144a002943\n2019-06-22 22:13:56+0000 [-] Log opened.\n2019-06-22 22:13:56+0000 [-] # iw reg set GY\n2019-06-22 22:13:57+0000 [-] # ifconfig wlx30144a002943 down\n2019-06-22 22:13:57+0000 [-] # iw dev wlx30144a002943 set monitor otherbss\n2019-06-22 22:13:57+0000 [-] # ifconfig wlx30144a002943 up\n2019-06-22 22:13:57+0000 [-] # iw dev wlx30144a002943 set channel 9 HT20\n2019-06-22 22:13:57+0000 [-] command failed: Operation not supported (-95)\n2019-06-22 22:13:57+0000 [-] Stopping reactor due to fatal error: RC 161: iw dev wlx30144a002943 set txpower fixed 58\n2019-06-22 22:13:57+0000 [-] Main loop terminated.\n2019-06-22 22:13:57+0000 [-] Exiting with code 1\n\n```","files":null}]}