{"author":{"id":"1f074489d945895bb210302fbff995dc666b223b4510531901cee946767163c9"},"ops":[{"type":6,"timestamp":1583864279,"nonce":"RUKE8cdR2wU2pMNv0eUMKKpveMQ=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlRWRpdDozNTg4NTU0Mjg="},"target":"73902c938b4ce02630f1c3d0c9f9d5ac0c28ea51b41e4025642379c0c881bcbe","message":"I've build 2 images using this procedure : \nhttps://github.com/svpcom/wifibroadcast/issues/53\n\nMy setup :\n\n    drone :\n    Pi2B + Pi cam + AWUS036ACH (rtl8812au)\n\n    gs :\n    Pi3B + 7 \" HDMI screen + AWUS1900 (rtl8814au) or ASUS AC56 (rtl8812au)\n\nBoth Pis are ethernet connected with my desktop, and I can ssh to them.\n\nThe 2 Pis are booting perfectly, and the 2 wifi boards are up and in monitor mode.\n\nBut using \"wfb-cli gs\" on the gs Pi, I can see that all 3 connections failed (refused by the other side)\n\nHere are the output of \"sudo python -m telemetry.server gs wlan0\" :\n\non drone :\n\nYves Chaufour, [10.03.20 16:03]\nHere are the output of \"sudo python -m telemetry.server gs wlan00\" :\n\non drone :\n\n```\n2020-03-10 14:56:17+0000 [-] Log opened.\n2020-03-10 14:56:17+0000 [-] # iw reg set BO\n2020-03-10 14:56:17+0000 [-] # ifconfig wlan0 down\n2020-03-10 14:56:17+0000 [-] # iw dev wlan0 set monitor otherbss\n2020-03-10 14:56:17+0000 [-] # ifconfig wlan0 up\n2020-03-10 14:56:17+0000 [-] # iw dev wlan0 set channel 161 HT20\n2020-03-10 14:56:17+0000 [-] Connect telem stream 2(RX), 1(TX) to 127.0.0.1:14550\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 58782\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 14600\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 50385\n2020-03-10 14:56:17+0000 [-] Telem RX: /usr/bin/wfb_rx -p 2 -u 14600 -K /etc/gs.key -k 1 -n 2 wlan0\n2020-03-10 14:56:17+0000 [-] Telem TX: /usr/bin/wfb_tx -p 1 -u 14601 -K /etc/gs.key -B 20 -G long -S 1 -L 0 -M 1 -k 1 -n 2 wlan0\n2020-03-10 14:56:17+0000 [-] AntennaFactory starting on 8001\n2020-03-10 14:56:17+0000 [-] Started telem rx\n2020-03-10 14:56:17+0000 [-] Started telem tx\n2020-03-10 14:56:17+0000 [-] Send video stream 3 to 127.0.0.1:5600\n2020-03-10 14:56:17+0000 [-] AntennaFactory starting on 8002\n2020-03-10 14:56:17+0000 [-] Started video rx\n2020-03-10 14:56:17+0000 [-] Video: /usr/bin/wfb_rx -p 3 -c 127.0.0.1 -u 5600 -K /etc/gs.key -k 8 -n 12 wlan0\n2020-03-10 14:56:17+0000 [-] Stopping reactor due to fatal error: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 50385 Closed)\n2020-03-10 14:56:17+0000 [main.AntennaFactory] (TCP Port 8002 Closed)\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 14600 Closed)\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 58782 Closed)\n2020-03-10 14:56:17+0000 [main.AntennaFactory] (TCP Port 8001 Closed)\n2020-03-10 14:56:17+0000 [-] Stopped RX telem rx with code 1\n2020-03-10 14:56:17+0000 [-] Stopped RX video rx with code 1\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 457, in callback\n            self._startRunCallbacks(result)\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 565, in _startRunCallbacks\n            self._runCallbacks()\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 651, in _runCallbacks\n            current.result = callback(current.result, *args, **kw)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/server.py\", line 319, in _init_services\n            defer.maybeDeferred(init_tunnel, profile, wlans)])\\\n        --- \u003cexception caught here\u003e ---\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n            result = f(*args, **kw)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/server.py\", line 435, in init_tunnel\n            tun_ep = TUNTAPTransport(reactor, p_in, cfg.ifname, cfg.ifaddr, mtu=settings.common.radio_mtu)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/tuntap.py\", line 61, in init\n            with closing(IPRoute()) as ip:\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/__init__.py\", line 89, in new\n            cls.register(cls.registry['class'])\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/__init__.py\", line 69, in getitem\n            [name], 0)\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/iproute.py\", line 109, in \u003cmodule\u003e\n            from pyroute2.netlink.rtnl.tcmsg import get_codel_parameters\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/tcmsg.py\", line 31, in \u003cmodule\u003e\n            _psched = open('/proc/net/psched', 'r')\n        exceptions.IOError: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n        Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.\n\n2020-03-10 14:56:18+0000 [-] Stopped TX telem tx with code 1\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n        Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.\n\n\n```\non gs :\n\n```\n2020-03-10 14:52:49+0000 [-] Log opened.                                                                              │\n2020-03-10 14:52:49+0000 [-] # iw reg set BO                                                                          │\n2020-03-10 14:52:49+0000 [-] # ifconfig wlan0 down                                                                    │\n2020-03-10 14:52:49+0000 [-] # iw dev wlan0 set monitor otherbss                                                      │\n2020-03-10 14:52:49+0000 [-] # ifconfig wlan0 up                                                                      │\n2020-03-10 14:52:49+0000 [-] # iw dev wlan0 set channel 161 HT20──────────────────────────────────────────────────────┘\n2020-03-10 14:52:49+0000 [-] Connect telem stream 2(RX), 1(TX) to 127.0.0.1:14550─────────────────────────────────────┐\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 38488Connection refused.                                    │\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 14600                                                       │\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 52844                                                       │\n2020-03-10 14:52:49+0000 [-] Telem RX: /usr/bin/wfb_rx -p 2 -u 14600 -K /etc/gs.key -k 1 -n 2 wlan0                   │\n2020-03-10 14:52:49+0000 [-] Telem TX: /usr/bin/wfb_tx -p 1 -u 14601 -K /etc/gs.key -B 20 -G long -S 2 -L 0 -M 1 -k 1 -n 2 wlan0                                                                                                             │\n2020-03-10 14:52:49+0000 [-] AntennaFactory starting on 8001                                                          │\n2020-03-10 14:52:49+0000 [-] Started telem rx                                                                         │\n2020-03-10 14:52:49+0000 [-] Started telem tx                                                                         │\n2020-03-10 14:52:49+0000 [-] Send video stream 3 to 127.0.0.1:5600                                                    │\n2020-03-10 14:52:49+0000 [-] AntennaFactory starting on 8002                                                          │\n2020-03-10 14:52:49+0000 [-] Started video rx─────────────────────────────────────────────────────────────────────────┘\n2020-03-10 14:52:49+0000 [-] Video: /usr/bin/wfb_rx -p 3 -c 127.0.0.1 -u 5600 -K /etc/gs.key -k 8 -n 12 wlan0\n2020-03-10 14:52:50+0000 [-] Stopping reactor due to fatal error: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 52844 Closed)\n2020-03-10 14:52:50+0000 [main.AntennaFactory] (TCP Port 8001 Closed)\n2020-03-10 14:52:50+0000 [main.AntennaFactory] (TCP Port 8002 Closed)\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 14600 Closed)\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 38488 Closed)\n2020-03-10 14:52:50+0000 [-] Main loop terminated.\n2020-03-10 14:52:50+0000 [-] Exiting with code 1\n```","files":null},{"type":6,"timestamp":1583864316,"nonce":"4ejHmf8s2GcubsW2AMobxXv4K+s=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlRWRpdDozNTg4NTU2Mjg="},"target":"73902c938b4ce02630f1c3d0c9f9d5ac0c28ea51b41e4025642379c0c881bcbe","message":"I've build 2 images using this procedure : \nhttps://github.com/svpcom/wifibroadcast/issues/53\n\nMy setup :\n\n    drone :\n    Pi2B + Pi cam + AWUS036ACH (rtl8812au)\n\n    gs :\n    Pi3B + 7 \" HDMI screen + AWUS1900 (rtl8814au) or ASUS AC56 (rtl8812au)\n\nBoth Pis are ethernet connected with my desktop, and I can ssh to them.\n\nThe 2 Pis are booting perfectly, and the 2 wifi boards are up and in monitor mode.\n\nBut using \"wfb-cli gs\" on the gs Pi, I can see that all 3 connections failed (refused by the other side)\n\nHere are the output of \"sudo python -m telemetry.server gs wlan0\" :\n\non drone :\n\n```\n2020-03-10 14:56:17+0000 [-] Log opened.\n2020-03-10 14:56:17+0000 [-] # iw reg set BO\n2020-03-10 14:56:17+0000 [-] # ifconfig wlan0 down\n2020-03-10 14:56:17+0000 [-] # iw dev wlan0 set monitor otherbss\n2020-03-10 14:56:17+0000 [-] # ifconfig wlan0 up\n2020-03-10 14:56:17+0000 [-] # iw dev wlan0 set channel 161 HT20\n2020-03-10 14:56:17+0000 [-] Connect telem stream 2(RX), 1(TX) to 127.0.0.1:14550\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 58782\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 14600\n2020-03-10 14:56:17+0000 [-] UDPProxyProtocol starting on 50385\n2020-03-10 14:56:17+0000 [-] Telem RX: /usr/bin/wfb_rx -p 2 -u 14600 -K /etc/gs.key -k 1 -n 2 wlan0\n2020-03-10 14:56:17+0000 [-] Telem TX: /usr/bin/wfb_tx -p 1 -u 14601 -K /etc/gs.key -B 20 -G long -S 1 -L 0 -M 1 -k 1 -n 2 wlan0\n2020-03-10 14:56:17+0000 [-] AntennaFactory starting on 8001\n2020-03-10 14:56:17+0000 [-] Started telem rx\n2020-03-10 14:56:17+0000 [-] Started telem tx\n2020-03-10 14:56:17+0000 [-] Send video stream 3 to 127.0.0.1:5600\n2020-03-10 14:56:17+0000 [-] AntennaFactory starting on 8002\n2020-03-10 14:56:17+0000 [-] Started video rx\n2020-03-10 14:56:17+0000 [-] Video: /usr/bin/wfb_rx -p 3 -c 127.0.0.1 -u 5600 -K /etc/gs.key -k 8 -n 12 wlan0\n2020-03-10 14:56:17+0000 [-] Stopping reactor due to fatal error: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 50385 Closed)\n2020-03-10 14:56:17+0000 [main.AntennaFactory] (TCP Port 8002 Closed)\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 14600 Closed)\n2020-03-10 14:56:17+0000 [UDPProxyProtocol (UDP)] (UDP Port 58782 Closed)\n2020-03-10 14:56:17+0000 [main.AntennaFactory] (TCP Port 8001 Closed)\n2020-03-10 14:56:17+0000 [-] Stopped RX telem rx with code 1\n2020-03-10 14:56:17+0000 [-] Stopped RX video rx with code 1\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 457, in callback\n            self._startRunCallbacks(result)\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 565, in _startRunCallbacks\n            self._runCallbacks()\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 651, in _runCallbacks\n            current.result = callback(current.result, *args, **kw)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/server.py\", line 319, in _init_services\n            defer.maybeDeferred(init_tunnel, profile, wlans)])\\\n        --- \u003cexception caught here\u003e ---\n          File \"/usr/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n            result = f(*args, **kw)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/server.py\", line 435, in init_tunnel\n            tun_ep = TUNTAPTransport(reactor, p_in, cfg.ifname, cfg.ifaddr, mtu=settings.common.radio_mtu)\n          File \"/usr/lib/python2.7/dist-packages/telemetry/tuntap.py\", line 61, in init\n            with closing(IPRoute()) as ip:\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/__init__.py\", line 89, in new\n            cls.register(cls.registry['class'])\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/__init__.py\", line 69, in getitem\n            [name], 0)\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/iproute.py\", line 109, in \u003cmodule\u003e\n            from pyroute2.netlink.rtnl.tcmsg import get_codel_parameters\n          File \"/usr/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/tcmsg.py\", line 31, in \u003cmodule\u003e\n            _psched = open('/proc/net/psched', 'r')\n        exceptions.IOError: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n        Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.\n\n2020-03-10 14:56:18+0000 [-] Stopped TX telem tx with code 1\n2020-03-10 14:56:18+0000 [-] Unhandled error in Deferred:\n2020-03-10 14:56:18+0000 [-] Unhandled Error\n        Traceback (most recent call last):\n        Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.\n\n\n```\non gs :\n\n```\n2020-03-10 14:52:49+0000 [-] Log opened.                                                                              │\n2020-03-10 14:52:49+0000 [-] # iw reg set BO                                                                          │\n2020-03-10 14:52:49+0000 [-] # ifconfig wlan0 down                                                                    │\n2020-03-10 14:52:49+0000 [-] # iw dev wlan0 set monitor otherbss                                                      │\n2020-03-10 14:52:49+0000 [-] # ifconfig wlan0 up                                                                      │\n2020-03-10 14:52:49+0000 [-] # iw dev wlan0 set channel 161 HT20──────────────────────────────────────────────────────┘\n2020-03-10 14:52:49+0000 [-] Connect telem stream 2(RX), 1(TX) to 127.0.0.1:14550─────────────────────────────────────┐\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 38488Connection refused.                                    │\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 14600                                                       │\n2020-03-10 14:52:49+0000 [-] UDPProxyProtocol starting on 52844                                                       │\n2020-03-10 14:52:49+0000 [-] Telem RX: /usr/bin/wfb_rx -p 2 -u 14600 -K /etc/gs.key -k 1 -n 2 wlan0                   │\n2020-03-10 14:52:49+0000 [-] Telem TX: /usr/bin/wfb_tx -p 1 -u 14601 -K /etc/gs.key -B 20 -G long -S 2 -L 0 -M 1 -k 1 -n 2 wlan0                                                                                                             │\n2020-03-10 14:52:49+0000 [-] AntennaFactory starting on 8001                                                          │\n2020-03-10 14:52:49+0000 [-] Started telem rx                                                                         │\n2020-03-10 14:52:49+0000 [-] Started telem tx                                                                         │\n2020-03-10 14:52:49+0000 [-] Send video stream 3 to 127.0.0.1:5600                                                    │\n2020-03-10 14:52:49+0000 [-] AntennaFactory starting on 8002                                                          │\n2020-03-10 14:52:49+0000 [-] Started video rx─────────────────────────────────────────────────────────────────────────┘\n2020-03-10 14:52:49+0000 [-] Video: /usr/bin/wfb_rx -p 3 -c 127.0.0.1 -u 5600 -K /etc/gs.key -k 8 -n 12 wlan0\n2020-03-10 14:52:50+0000 [-] Stopping reactor due to fatal error: [Errno 2] No such file or directory: '/proc/net/psched'\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 52844 Closed)\n2020-03-10 14:52:50+0000 [main.AntennaFactory] (TCP Port 8001 Closed)\n2020-03-10 14:52:50+0000 [main.AntennaFactory] (TCP Port 8002 Closed)\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 14600 Closed)\n2020-03-10 14:52:50+0000 [UDPProxyProtocol (UDP)] (UDP Port 38488 Closed)\n2020-03-10 14:52:50+0000 [-] Main loop terminated.\n2020-03-10 14:52:50+0000 [-] Exiting with code 1\n```","files":null},{"type":3,"timestamp":1583863903,"nonce":"D153pVvE04AMoC101QckzqK6/fg=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU5NzIzNTA5Mw==","github-url":"https://github.com/svpcom/wfb-ng/issues/55#issuecomment-597235093"},"message":"```\nFile \"/usr/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/tcmsg.py\", line 31, in \u003cmodule\u003e\n            _psched = open('/proc/net/psched', 'r')\n        exceptions.IOError: [Errno 2] No such file or directory: '/proc/net/psched'\n```\n\nIt seems that I'm missing \"/proc/net/psched\".\nDon't now what it means ...","files":null}]}